"""Local CAAC / CCAR corpus connector.

Searches the staged ``legal_helper/rag/corpus/caac_ccar`` Markdown corpus and
manifest generated by ``scripts/fetch_caac_corpus.py``. This is intentionally
deterministic: use it for exact document / CCAR-part / article lookup, then
use RAG for semantic expansion across the same corpus.

About 30% of CAAC source pages embed the statute text only as a PDF
attachment, so the matching Markdown body is a stub. ``caac_local_search`` and
``caac_local_fetch`` detect these stubs and prefer non-stub siblings (same
normalized title), falling back to the stub only if no full-text version
exists. Per-entry status from ``scripts/flag_expired_corpus.py --apply``
(``corpus_status``, ``superseded_by``) is honoured when present.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Optional

import yaml
from anthropic import beta_tool

_REPO_ROOT = Path(__file__).resolve().parents[2]
CORPUS_ROOT = _REPO_ROOT / "legal_helper" / "rag" / "corpus" / "caac_ccar"
MANIFEST_PATH = CORPUS_ROOT / "manifest.yaml"

_STUB_BODY_CHAR_LIMIT = 200
_ATTACHMENT_REF_RE = re.compile(
    r"附件\s*[:：][\s\S]{0,400}\.(pdf|docx?|doc)[^\n]*", re.IGNORECASE
)
_EXPIRED_VALIDITY_TOKENS = ("失效", "废止", "已废止", "历史版本")
_PAREN_RE = re.compile(r"[（(][^）)]*[）)]")


def _norm(text: str) -> str:
    return re.sub(r"\s+", "", text or "").strip()


def _norm_title(title: str | None) -> str:
    if not title:
        return ""
    return _norm(_PAREN_RE.sub("", title))


def _load_manifest() -> list[dict[str, Any]]:
    if not MANIFEST_PATH.is_file():
        return []
    raw = yaml.safe_load(MANIFEST_PATH.read_text(encoding="utf-8")) or {}
    return [dict(e) for e in raw.get("files") or [] if e.get("file")]


def _read_text(rel: str) -> str:
    path = (CORPUS_ROOT / rel).resolve()
    try:
        path.relative_to(CORPUS_ROOT.resolve())
    except ValueError:
        return ""
    if path.suffix.lower() != ".md" or not path.is_file():
        return ""
    return path.read_text(encoding="utf-8", errors="ignore")


def _body_after_heading(text: str) -> str:
    parts = text.split("## 正文", 1)
    return parts[1] if len(parts) == 2 else text


def _classify_body(text: str) -> tuple[bool, int]:
    """Return ``(is_stub, body_chars_excluding_attachment_refs)``."""
    body = _body_after_heading(text)
    if not body:
        return True, 0
    has_attachment = bool(_ATTACHMENT_REF_RE.search(body))
    cleaned = _ATTACHMENT_REF_RE.sub("", body)
    cleaned = re.sub(r"附件\s*[:：]\s*$", "", cleaned, flags=re.MULTILINE)
    cleaned = re.sub(r"\s+", "", cleaned)
    body_chars = len(cleaned)
    is_stub = body_chars < _STUB_BODY_CHAR_LIMIT and (
        has_attachment or body_chars < 60
    )
    return is_stub, body_chars


def _doc_entries() -> list[dict[str, Any]]:
    return [e for e in _load_manifest() if e.get("file_kind") == "source_page"]


def _entry_status(entry: dict[str, Any], text: str) -> dict[str, Any]:
    """Combine manifest-annotated status with on-the-fly stub detection."""
    manifest_status = str(entry.get("corpus_status") or "")
    flags = {tok for tok in manifest_status.split(",") if tok}
    is_stub, body_chars = _classify_body(text)
    if is_stub:
        flags.add("pdf_stub")
    validity = entry.get("validity") or ""
    if any(tok in validity for tok in _EXPIRED_VALIDITY_TOKENS):
        flags.add("explicit_expired")
    return {
        "flags": sorted(flags),
        "is_stub": is_stub,
        "body_chars": body_chars,
        "superseded_by": entry.get("superseded_by"),
    }


def _match_filters(
    entry: dict[str, Any],
    *,
    category: str,
    ccar_part: str,
    title: str,
    validity: str,
) -> bool:
    if category and entry.get("corpus_category") != category:
        return False
    if validity and validity not in str(entry.get("validity") or ""):
        return False
    if ccar_part:
        hay = " ".join(
            str(entry.get(k) or "") for k in ("ccar_part", "cite_prefix", "title")
        ).lower()
        if ccar_part.lower() not in hay:
            return False
    if title and title not in str(entry.get("title") or ""):
        return False
    return True


def _score(entry: dict[str, Any], text: str, query: str) -> float:
    if not query:
        return 1.0
    q = query.lower()
    title = str(entry.get("title") or "").lower()
    ccar = str(entry.get("ccar_part") or "").lower()
    docno = str(entry.get("document_number") or "").lower()
    body = text.lower()
    score = 0.0
    if q == title or q == ccar:
        score += 100.0
    if q in title:
        score += 40.0
    if q in ccar:
        score += 35.0
    if q in docno:
        score += 25.0
    if q in body:
        score += min(20.0, body.count(q) * 2.0)
    for token in [t for t in re.split(r"[\s,，;；]+", query) if len(t) >= 2]:
        tl = token.lower()
        if tl in title:
            score += 8.0
        if tl in ccar:
            score += 8.0
        if tl in body:
            score += min(6.0, body.count(tl))
    return score


def _snippet(text: str, query: str, limit: int = 500) -> str:
    clean = _norm(text)
    if not clean:
        return ""
    if query:
        idx = clean.lower().find(query.lower())
        if idx >= 0:
            start = max(0, idx - limit // 3)
            return clean[start : start + limit]
    return clean[:limit]


def _article_pattern(article: str) -> re.Pattern[str] | None:
    article = _norm(article)
    if not article:
        return None
    if article.startswith("第") and article.endswith("条"):
        label = re.escape(article)
    elif article.isdigit():
        label = rf"第\s*{article}\s*条"
    else:
        label = re.escape(article)
    return re.compile(
        rf"(?m)^\s*{label}[^\n]*(?:\n(?!\s*第[一二三四五六七八九十百千万零〇0-9]+\s*条)[^\n]*)*"
    )


def _extract_article(text: str, article: str) -> str:
    pat = _article_pattern(article)
    if not pat:
        return ""
    match = pat.search(text)
    return _norm(match.group(0)) if match else ""


def _candidate_entries(identifier: str) -> list[dict[str, Any]]:
    """Return every entry matching ``identifier`` by file, stem, CCAR part, or title.

    Unlike the legacy ``_find_entry`` this returns *all* matches so the caller
    can rank them (stub vs full-text, current vs superseded, etc.). Order
    within the returned list is: exact file/stem first, then ccar_part, then
    title substring; ties keep manifest order.
    """
    ident = identifier.strip()
    if not ident:
        return []
    entries = _doc_entries()
    seen: set[str] = set()
    out: list[dict[str, Any]] = []

    def _add(entry: dict[str, Any]) -> None:
        key = str(entry.get("file"))
        if key in seen:
            return
        seen.add(key)
        out.append(entry)

    for e in entries:
        if ident == e.get("file") or ident == Path(str(e.get("file"))).stem:
            _add(e)
    low = ident.lower()
    for e in entries:
        if low == str(e.get("ccar_part") or "").lower():
            _add(e)
    norm_ident = _norm_title(ident)
    for e in entries:
        title = str(e.get("title") or "")
        if ident in title:
            _add(e)
        elif norm_ident and norm_ident in _norm_title(title):
            _add(e)
    return out


def _rank_candidates(
    candidates: list[dict[str, Any]], article: str
) -> list[tuple[dict[str, Any], str, str, dict[str, Any]]]:
    """Sort candidates by usefulness for the caller.

    Returns a list of ``(entry, text, article_text, status)`` tuples sorted
    best-first. The ranking prefers, in order:

      1. Entries whose body contains the requested article (when ``article``
         is supplied).
      2. Non-stub bodies over PDF-only stubs.
      3. Entries not flagged ``explicit_expired`` / ``superseded``.
      4. Entries with later ``publish_date``.
    """
    enriched: list[tuple[dict[str, Any], str, str, dict[str, Any]]] = []
    for entry in candidates:
        text = _read_text(str(entry.get("file")))
        status = _entry_status(entry, text)
        article_text = _extract_article(text, article) if article else ""
        enriched.append((entry, text, article_text, status))

    def sort_key(item: tuple[dict[str, Any], str, str, dict[str, Any]]):
        entry, _text, article_text, status = item
        has_article = bool(article_text) if article else False
        non_stub = not status["is_stub"]
        not_expired = not (
            "explicit_expired" in status["flags"] or "superseded" in status["flags"]
        )
        # Larger tuple ⇒ higher priority (sorted reverse=True below).
        return (
            int(has_article),
            int(non_stub),
            int(not_expired),
            str(entry.get("publish_date") or ""),
            status["body_chars"],
        )

    enriched.sort(key=sort_key, reverse=True)
    return enriched


def _result_payload(
    entry: dict[str, Any],
    text: str,
    article_text: str,
    article: str,
    status: dict[str, Any],
    max_chars: int,
) -> dict[str, Any]:
    return {
        "title": entry.get("title"),
        "file": entry.get("file"),
        "source_url": entry.get("source_url"),
        "legal_category": entry.get("legal_category"),
        "ccar_part": entry.get("ccar_part"),
        "document_number": entry.get("document_number"),
        "validity": entry.get("validity"),
        "publish_date": entry.get("publish_date"),
        "adoption_date": entry.get("adoption_date"),
        "cite_prefix": entry.get("cite_prefix"),
        "corpus_status": entry.get("corpus_status"),
        "superseded_by": status.get("superseded_by"),
        "is_stub": status["is_stub"],
        "body_chars": status["body_chars"],
        "flags": status["flags"],
        "article": article or "",
        "article_text": article_text,
        "text": article_text or text[:max_chars],
        "truncated": not article_text and len(text) > max_chars,
    }


@beta_tool
def caac_local_search(
    query: str,
    category: Optional[str] = None,
    ccar_part: str = "",
    title: str = "",
    validity: str = "",
    article: str = "",
    per_page: int = 8,
    include_stubs: bool = True,
) -> str:
    """Search the local CAAC / CCAR corpus staged from caac.gov.cn.

    Prefer this for deterministic PRC aviation lookup: exact title, CCAR part
    number, document number, validity status, source URL, and article pinpoints.
    Each result is tagged with ``is_stub`` (markdown body is only a PDF
    attachment), ``flags`` (``pdf_stub``, ``explicit_expired``, ``superseded``,
    ``future_effective``), and ``superseded_by`` so the caller can decide
    whether to cite or skip.

    Args:
        query: Keyword, title fragment, document number, CCAR part, or phrase.
        category: Optional ``laws`` or ``ccar`` filter.
        ccar_part: Optional CCAR part filter, e.g. ``CCAR-121-R7``.
        title: Optional Chinese title substring filter.
        validity: Optional CAAC validity filter, e.g. ``有效`` or ``失效``.
        article: Optional article label/number to extract from matching docs,
            e.g. ``第十五条`` or ``15``. When supplied, the search prefers
            entries whose body actually contains that article.
        per_page: Results to return (1-20).
        include_stubs: If ``False``, drop entries whose Markdown body is just
            a PDF attachment reference. Defaults to ``True`` so the caller
            still sees them with ``is_stub=True``.
    """
    per_page = max(1, min(int(per_page), 20))
    cat = (category or "").strip()
    if cat and cat not in {"laws", "ccar"}:
        return json.dumps(
            {"error": "category must be 'laws', 'ccar', or empty"},
            ensure_ascii=False,
        )

    hits: list[tuple[float, dict[str, Any], str, str, dict[str, Any]]] = []
    for entry in _doc_entries():
        if not _match_filters(
            entry,
            category=cat,
            ccar_part=ccar_part,
            title=title,
            validity=validity,
        ):
            continue
        text = _read_text(str(entry.get("file")))
        status = _entry_status(entry, text)
        if not include_stubs and status["is_stub"]:
            continue
        article_text = _extract_article(text, article) if article else ""
        score = _score(entry, text, query)
        # When the caller asked for a specific article, an entry that actually
        # contains it is informative even with a zero keyword score.
        if query and score <= 0 and not article_text:
            continue
        hits.append((score, entry, text, article_text, status))

    def sort_key(item):
        item_score, entry, _text, item_article_text, item_status = item
        return (
            int(bool(item_article_text)) if article else 0,
            item_score,
            int(not item_status["is_stub"]),
            int(
                not (
                    "explicit_expired" in item_status["flags"]
                    or "superseded" in item_status["flags"]
                )
            ),
            str(entry.get("validity") or "") == "有效",
            str(entry.get("publish_date") or ""),
        )

    hits.sort(key=sort_key, reverse=True)
    results: list[dict[str, Any]] = []
    for hit_score, entry, text, article_text, status in hits[:per_page]:
        results.append(
            {
                "score": hit_score,
                "title": entry.get("title"),
                "file": entry.get("file"),
                "source_url": entry.get("source_url"),
                "legal_category": entry.get("legal_category"),
                "ccar_part": entry.get("ccar_part"),
                "document_number": entry.get("document_number"),
                "validity": entry.get("validity"),
                "publish_date": entry.get("publish_date"),
                "adoption_date": entry.get("adoption_date"),
                "cite_prefix": entry.get("cite_prefix"),
                "corpus_status": entry.get("corpus_status"),
                "superseded_by": status.get("superseded_by"),
                "is_stub": status["is_stub"],
                "body_chars": status["body_chars"],
                "flags": status["flags"],
                "article_text": article_text,
                "snippet": article_text or _snippet(text, query),
            }
        )
    return json.dumps(
        {
            "source": "local caac_ccar corpus",
            "query": query,
            "category": cat or "all",
            "count": len(results),
            "results": results,
        },
        ensure_ascii=False,
    )


@beta_tool
def caac_local_fetch(
    identifier: str,
    article: str = "",
    max_chars: int = 12000,
    prefer_full_text: bool = True,
) -> str:
    """Fetch one local CAAC / CCAR document by file, title, or CCAR part.

    Many CAAC source pages embed the statute text only as a PDF attachment,
    so the matching Markdown is a stub. When the requested identifier matches
    multiple entries (e.g. several revisions of the same title), this picks
    the entry that actually contains usable text: when ``article`` is given,
    the entry whose body contains that article; otherwise prefer non-stub,
    non-superseded, non-expired, latest ``publish_date``. The losing matches
    are returned in ``alternates`` with their status so the caller can pivot.

    Args:
        identifier: ``documents/...md`` path, source-page stem, exact CCAR
            part, or title substring. Title matches are normalized by
            stripping parenthetical version suffixes such as ``（2021年版）``
            so different revisions of the same statute are considered together.
        article: Optional article label/number to extract, e.g. ``第十五条``
            or ``124``. Drives candidate selection — see above.
        max_chars: Maximum full-text characters to return (1000-40000).
        prefer_full_text: When ``True`` (default), pick the entry whose
            Markdown body has statute text over an otherwise-better stub
            entry. Set ``False`` to honour the legacy validity-first ranking.
    """
    max_chars = max(1000, min(int(max_chars), 40000))
    candidates = _candidate_entries(identifier)
    if not candidates:
        return json.dumps(
            {"error": "CAAC document not found", "identifier": identifier},
            ensure_ascii=False,
        )

    ranked = _rank_candidates(candidates, article)
    if not prefer_full_text:
        # Legacy ordering: ignore stub status, keep article-presence + validity
        # + publish_date as primary keys.
        ranked.sort(
            key=lambda x: (
                int(bool(x[2])) if article else 0,
                str(x[0].get("validity") or "") == "有效",
                str(x[0].get("publish_date") or ""),
            ),
            reverse=True,
        )

    primary_entry, primary_text, primary_article_text, primary_status = ranked[0]
    note: Optional[str] = None
    if primary_status["is_stub"]:
        note = (
            "primary match is a PDF-attachment stub; no statute text is "
            "available in the local Markdown — fetch the source_url PDF or "
            "consult PKULaw / flk.npc.gov.cn for the article body"
        )
    elif (
        article
        and not primary_article_text
        and any(
            entry.get("file") != primary_entry.get("file")
            for entry, *_ in ranked
        )
    ):
        note = (
            "article not found in primary match; check alternates for a "
            "revision that contains the requested article"
        )

    primary_payload = _result_payload(
        primary_entry,
        primary_text,
        primary_article_text,
        article,
        primary_status,
        max_chars,
    )
    alternates: list[dict[str, Any]] = []
    for entry, text, article_text, status in ranked[1:]:
        alternates.append(
            {
                "title": entry.get("title"),
                "file": entry.get("file"),
                "source_url": entry.get("source_url"),
                "ccar_part": entry.get("ccar_part"),
                "validity": entry.get("validity"),
                "publish_date": entry.get("publish_date"),
                "corpus_status": entry.get("corpus_status"),
                "superseded_by": status.get("superseded_by"),
                "is_stub": status["is_stub"],
                "body_chars": status["body_chars"],
                "flags": status["flags"],
                "has_article": bool(article_text),
            }
        )

    out: dict[str, Any] = {
        "source": "local caac_ccar corpus",
        "identifier": identifier,
        "match_count": len(ranked),
        **primary_payload,
        "alternates": alternates,
    }
    if note:
        out["note"] = note
    return json.dumps(out, ensure_ascii=False)
